[package]
name = "sync-lsp-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
serde = { version = "1.0.192", features = ["derive"] }
sync-lsp = { path = "../sync-lsp" }
